/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterComp: typeof import('./src/components/FooterComp.vue')['default']
    Frame: typeof import('./src/components/Frame.vue')['default']
    Frame1: typeof import('./src/components/Frame1.vue')['default']
    FRAME2: typeof import('./src/components/FRAME2.vue')['default']
    Frame3: typeof import('./src/components/Frame3.vue')['default']
    GroupFrame: typeof import('./src/components/GroupFrame.vue')['default']
    CheckpointFeatures: typeof import('./src/components/CheckpointFeatures.vue')['default']
    LangChooser: typeof import('./src/components/LangChooser.vue')['default']
    MainCarousel: typeof import('./src/components/MainCarousel.vue')['default']
    MainComp: typeof import('./src/components/MainComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
