/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BenefitsSection: typeof import('./src/components/BenefitsSection.vue')['default']
    BenefitTwoContent: typeof import('./src/components/BenefitTwoContent.vue')['default']
    BotherSection: typeof import('./src/components/BotherSection.vue')['default']
    CaseStudySection: typeof import('./src/components/CaseStudySection.vue')['default']
    ContactLandingSection: typeof import('./src/components/ContactLandingSection.vue')['default']
    FooterSection: typeof import('./src/components/FooterSection.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HeaderMenu: typeof import('./src/components/HeaderMenu.vue')['default']
    ImmersiveSection: typeof import('./src/components/ImmersiveSection.vue')['default']
    LandingSection: typeof import('./src/components/LandingSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestimonialsSection: typeof import('./src/components/TestimonialsSection.vue')['default']
  }
}
